apiVersion: v1
kind: Secret
metadata:
    name: slack-credential
    namespace: report-bot
stringData:
    signing_secret: ENC[AES256_GCM,data:pr8g6plIU22sl5T29XI95P/cebH/KpxkGyva+IRKRWQ=,iv:e6W96ZVpoBgeQD6M70o47xWMRE5+LfHunXKvLkOnVWE=,tag:Sc+DVM9pQHvw7OIpRrJC5A==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZ2pvT29zUkdMM3hoMTlP
            ZDhtcU1sckhnVGZWN2JOUjRnWjdKRUwvZldvCk9tcENlcW8rbkRRZU9DVVdYLzZO
            VE5SemN1V1pJcjhhVXhhckJyeFZyMmMKLS0tIDcxUmtQaEF1ZkJKUEluQW1oSjFy
            aEloWC9lYXVRLzBaR2xsOWczRnk4MDQKeDo2nvv63fPSE5rZO2wG+cvf9sXvN6Up
            F3r6tovypgLLWXgkqZGEhTL0zTDSfr8Hh2u2ZLCedeMEuIiXOqyoAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u9tkn00xqk4rfa9y9mkyfyts9vqw4vpvh4aa74egqdg8z73stapqhu5pu4
    encrypted_regex: ^(stringData|data)$
    lastmodified: "2026-09-13T05:34:47Z"
    mac: ENC[AES256_GCM,data:Bmg9KWzj4PVvIHgosE4k5s2PMs2PSm+J0CPPguNdKkceiaKqIGPZa4EYIn0lG58jsvoG6kggTy04EPftllQchn9+ytBkHxxTcX/kgR1OLOLPBmHIP89zGHWfmRXVCWthKjKs0EMs8xFXuANOv29ZBQ62JGZQT+6AX8Q+lYEZTTQ=,iv:syOTjAyhCQPPV8aB1rFBUPB+ldE1ZvzZ3uxM2Fae4dc=,tag:vaDDCyVDgU3IvZTxbVr2tA==,type:str]
    version: 3.13.0
