apiVersion: v1
kind: Secret
metadata:
    name: smtp-credential
    namespace: report-bot
stringData:
    password: ENC[AES256_GCM,data:/sC2p7piXpg=,iv:QjdnT6oTaf3kOAZw62vHj7YUAktRrqshZdYBk7I9Ohs=,tag:vfNWq8aXPslnJy/RYy3+Hg==,type:str]
    username: ENC[AES256_GCM,data:7MeIcxqxHO28G1pqiP+8hvUJKQ==,iv:REYZ/GkhLGryj7jcUVrE3ze+u7jv6Y4SFuwLdjffj7I=,tag:tWvzkOr1DuviAupll/ObNw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYkI2UlNrWUVwdlZ4d1Vm
            Sk44NnY2K094RmppS0w2bXRIenIzQU1ub3hRCk9GRjlEZk1kVk9nRVJ1ajN5eDN1
            K1N5cUFHMnVvRHprbENWYURmSXp4Q1UKLS0tIE9abjVIT3haWFZVYkxLZTdyK3lk
            U1c3eEh4MnNCY1ZiLys3SnJPak5mdXcK+RT72N/ZVN8Uh5/IZecSbMIAL8dlOKWz
            lBIezQ8CD+yq1k7krgTbGBeJwoduaQZ7+qaKJoPAKxqb1gR8ikfpJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u9tkn00xqk4rfa9y9mkyfyts9vqw4vpvh4aa74egqdg8z73stapqhu5pu4
    encrypted_regex: ^(stringData|data)$
    lastmodified: "2026-09-12T03:46:14Z"
    mac: ENC[AES256_GCM,data:t+wZEeYFxRRLJiy/aLnmgSJgUg1QT6cYgRsTh/AGxfmjWacWZilMQe5Jb3t4OfQKz0hNekgYd6PCW5Z7BjnR5f8IvfQZy1lYGIDL07DwUe0V3bKAd6F2olEkqdWI4JJK5pvZ21pJ9nswOW9doBv491neC9turUAScpof15AbuUU=,iv:mDMIiYoxWZMp9VEf6Sj3Bf63ZwgGLycV0NNVJ7qaPn0=,tag:4/1CJsivt+XBAH/G6xQ8fg==,type:str]
    version: 3.13.0
