apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: steam-bot

resources:
- ../../base

patches:
- path: patch-service.yaml

images:
- name: steam-bot-image
  newName: ghcr.io/yk2906/steam-bot
  newTag: 8038ece289a21fb8b160aef35d11498232cd26a6
