apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: patch-service.yaml

images:
- name: steam-bot-image
  newName: ghcr.io/yk2906/steam-bot
  newTag: 73a7a24dcc082c17c6601660ce7b845276246557
