apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: steam-bot

resources:
- ../../base

replacements:
- path: sync-cronworkflow-image.yaml

images:
- name: steam-bot-image
  newName: ghcr.io/yk2906/steam-bot
  newTag: 75399572ff9ab06dfa167706ac611c9a1421c81e
