apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: report-bot

resources:
- ../../base

images:
- name: report-bot-image
  newName: ghcr.io/yk2906/report-bot
  newTag: 40e80495b7b6ff3c491f7dba576906c928fdf55b
