apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: report-bot

resources:
- ../../base

images:
- name: report-bot-image
  newName: ghcr.io/yk2906/report-bot
  newTag: 6162bc111a86d88c4d97ae5abe2de6b29627e4b5
