apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: report-bot

resources:
- ../../base

images:
- name: report-bot-image
  newName: ghcr.io/yk2906/report-bot
  newTag: e20899a43d3f598b9afdf4a5b8a3f04f833b84d7
