- name: Create Kubernetes user with root-level access
  hosts: all
  become: true
  vars:
    k8s_user: k8s

  tasks:
    - name: Create the k8s user with home directory and bash shell
      user:
        name: "{{ k8s_user }}"
        shell: /bin/bash
        create_home: yes

    - name: Add user to sudo group
      user:
        name: "{{ k8s_user }}"
        groups: sudo
        append: yes

    - name: Add user to docker group
      user:
        name: "{{ k8s_user }}"
        groups: docker
        append: yes

    - name: Allow passwordless sudo for k8s user
      copy:
        dest: "/etc/sudoers.d/{{ k8s_user }}"
        content: "{{ k8s_user }} ALL=(ALL) NOPASSWD:ALL\n"
        owner: root
        group: root
        mode: '0440'

    - name: Remove password for k8s user (for su without password)
      command: passwd -d "{{ k8s_user }}"
      args:
        warn: false

