apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weather

resources:
- ../../base

replacements:
- path: sync-cronworkflow-image.yaml

images:
- name: weather-image
  newName: ghcr.io/yk2906/weather
  newTag: 6e5d98cad1d58e6e03c8f4880afb60d118e2c908
