apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  labels:
    app: weather
spec:
  replicas: 0
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
        - name: weather-container
          image: weather-image:latest
          imagePullPolicy: Always
