apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - serviceaccount-workflow.yaml
  - role-workflow.yaml
  - rolebinding-workflow.yaml
  - cronworkflow-weather-daily.yaml
